// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetEntryByDate(arg1:string):Promise<main.JournalEntry>;

export function GetTodayEntry():Promise<main.JournalEntry>;

export function LoadAllEntries():Promise<Array<main.JournalEntry>>;

export function SaveEntry(arg1:main.JournalEntry):Promise<void>;
