// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEntryByDate(arg1) {
  return window['go']['main']['App']['GetEntryByDate'](arg1);
}

export function GetTodayEntry() {
  return window['go']['main']['App']['GetTodayEntry']();
}

export function LoadAllEntries() {
  return window['go']['main']['App']['LoadAllEntries']();
}

export function SaveEntry(arg1) {
  return window['go']['main']['App']['SaveEntry'](arg1);
}
